### ISSUE TITLE
Finalise `semantic-release` process

### ISSUE THREAD

**Issue by myii** [n-rodriguez/telegraf-formula#1]
Hey @n-rodriguez, nice work!  You disappeared off Freenode before I got a chance to respond so thought I'd pay you a visit.

I've only had a cursory look over this, so no major feedback as of yet.  I _did_ notice that `semantic-release` hasn't started churning out versions yet.  What's your plan for that?  A couple of thoughts:

1. In all cases, you may want to start the first release manually, otherwise `v1.0.0` will be created.
1. I noticed that you don't have a `.travis.yml` -- I suppose that's because there aren't any tests just yet.  In the meanwhile, you may want a purely `semantic-release` setup, with little or no Kitchen involvement.  You can see how I'm doing that in the [`ssf-formula`](https://github.com/myii/ssf-formula/blob/ac88c9e5125a9d7f570d061df67a30b0981bc9a0/.travis.yml) at the current time.

**Comment by n-rodriguez** [comment]
@myii thanks for your feedback!

To point out some changes : I use a different naming scheme for states id. 
See 
* https://github.com/n-rodriguez/telegraf-formula/blob/master/telegraf/config/file.sls
* https://github.com/n-rodriguez/telegraf-formula/blob/master/telegraf/package/install.sls.

I find it clearer specially when running states. (I set `state_output: changes_id` and `state_tabular: true` in Salt master config)

Here how it looks in console:

```console
root@salt:~# salt web2.foo.bar state.apply install.telegraf
web2.foo.bar:
22:30:49.624654 [ 25.098 ms]        pkg.installed  Clean     Name: telegraf/package/install
22:30:49.649876 [ 12.081 ms]        pkg.installed  Clean     Name: telegraf/package/pip/install
22:30:49.910729 [1347.994 ms]        pip.installed  Clean     Name: telegraf/package/toml/install
22:30:51.260636 [  47.05 ms]       file.managed    Clean     Name: telegraf/config/install
22:30:51.308293 [ 23.586 ms]    service.running    Clean     Name: telegraf/service/running

Summary for web2.foo.bar
------------
Succeeded: 5
Failed:    0
------------
Total states run:     5
Total run time:   1.456 s
```

**Comment by n-rodriguez** [comment]
About Kitchen and testing : the thing is that most of the time telegraf is not packaged by the distro so you need to use InfluxData repositories to install it : https://docs.influxdata.com/telegraf/v1.11/introduction/installation/#installation.

Fortunately InfluxData provides packages repositories for (almost) all distros, but we might need to implement it in the formula.

Do you know how to handle such a case?

Thank you!

**Comment by myii** [comment]
@n-rodriguez Interesting naming scheme.  I still prefer underscores for my own state names, since I like being able to highlight the whole state name in one action with my editor.

I was just about to mention the issue with installing `telegraf` when you've just added a new comment.  Doesn't `pkgrepo` do the trick for you?  Let me check for a formula example...

**Comment by n-rodriguez** [comment]
After that, testing should be a breath : config file is in toml :)

**Comment by n-rodriguez** [comment]
> @n-rodriguez Interesting naming scheme. I still prefer underscores for my own state names, since I like being able to highlight the whole state name in one action with my editor.

The idea behind that is to ease human reading / computer parsing

**Comment by myii** [comment]
@n-rodriguez In the meantime, here was an effort at getting `semantic-release` finalised for this repo (was going to make a PR):

* https://travis-ci.org/myii/telegraf-formula/builds/573231981

`telegraf` wasn't recognised as a package for any of the distros!

**Comment by n-rodriguez** [comment]
> `telegraf` wasn't recognised as a package for any of the distros!

yeah, it doesn't surprise me ^^

**Comment by n-rodriguez** [comment]
Got one : https://github.com/saltstack-formulas/nginx-formula/blob/master/nginx/pkg.sls

But I find it a bit complex. A split version could be easier to read.

**Comment by myii** [comment]
The same `pkgrepo` method is used in formulas like `deepsea`, `golang`, `grafana` and `prometheus`.

**Comment by myii** [comment]
I'll try and link one in a minute, my laptop is currently "having a moment".

**Comment by myii** [comment]
@n-rodriguez So the [`repo` component](https://github.com/saltstack-formulas/deepsea-formula/tree/fc3869f75bbf7939de9dac897974c9162e442e80/deepsea/package/repo) used from [`install.sls`](https://github.com/saltstack-formulas/deepsea-formula/blob/fc3869f75bbf7939de9dac897974c9162e442e80/deepsea/package/install.sls#L8-L11).

**Comment by n-rodriguez** [comment]
> @n-rodriguez So the [`repo` component](https://github.com/saltstack-formulas/deepsea-formula/tree/fc3869f75bbf7939de9dac897974c9162e442e80/deepsea/package/repo) used from [`install.sls`](https://github.com/saltstack-formulas/deepsea-formula/blob/fc3869f75bbf7939de9dac897974c9162e442e80/deepsea/package/install.sls#L8-L11).

Thanks! Looks nice!

**Comment by myii** [comment]
You're welcome, hope it works out.

**Comment by n-rodriguez** [comment]
> You're welcome, hope it works out.

well... yes and no... I got some issues with python-toml....

If I use `python-toml` from pip, the state breaks because toml is not found...
If I re-run the state it works. But it would be better to not have to re-run the state otherwise it will never work in CI.

If I use `python-pytoml` from distro repo, it works for most distros (see [Travis](https://travis-ci.com/n-rodriguez/telegraf-formula/builds/123805754?utm_medium=notification&utm_source=email))

Although `python-pytoml` (and `python3-pytoml`) is still included in recent distros (https://packages.debian.org/buster/python3-pytoml), it is marked as deprecated : https://pypi.org/project/pytoml/

If I use `python-toml` from distro repo it breaks : https://github.com/uiri/toml/issues/247#issuecomment-523164353

What would you do?

**Comment by n-rodriguez** [comment]
About the broken jobs : 

Fedora: I don't if RedHat/CentOS repos are compatible with Fedora

OpenSuse: here the Telegraf doc :

```sh
There are RPM packages provided by openSUSE Build Service for SUSE Linux users:
# add go repository
zypper ar -f obs://devel:languages:go/ go
# install latest telegraf
zypper in telegraf
```
I don't know how to translate this in pillars and there is no `python-pytoml` package by default (except using backports repo) so the pip solution wins here (if it works)

RedHat 6 : I don't know yet ^^

**Comment by n-rodriguez** [comment]
About RedHat6 : did you know? https://github.com/moby/moby/issues/9856#issuecomment-113195713

**Comment by n-rodriguez** [comment]
The only formula that also use toml is (of course) influxdb : https://github.com/search?q=org%3Asaltstack-formulas+toml&type=Code

The idea here is to find a common/global solution for toml config files.

**Comment by myii** [comment]
@n-rodriguez Sounds like a lot of fun!  Have you tried running all of the instances, to see how many pass?  Worst case, you could you more of the recent ones to make up the numbers (i.e. `2019.2` and newer).

**Comment by n-rodriguez** [comment]
> Have you tried running all of the instances, to see how many pass?

Good catch :+1:  It's running!

**Comment by myii** [comment]
@n-rodriguez OK, I'm running a test as well, with `amazonlinux` added as well:

* https://travis-ci.org/myii/telegraf-formula/builds/574566692

**Comment by n-rodriguez** [comment]
results : https://travis-ci.com/n-rodriguez/telegraf-formula

* redhat-centos-7-develop-py3 is totally broken
* OpenSuse : repo is not configured yet

**Comment by myii** [comment]
@n-rodriguez We've both got the same 10 working, so that's double confirmation.  You could go with something like this for the time being and then improve it later:

```yaml
    - INSTANCE: debian-debian-9-develop-py3
    ...
    - INSTANCE: debian-ubuntu-1804-2019-2-py3
    - INSTANCE: redhat-centos-7-2019-2-py3
    ...
    - INSTANCE: debian-debian-9-2018-3-py2
    ...
    - INSTANCE: redhat-centos-7-2018-3-py2
    - INSTANCE: debian-ubuntu-1604-2017-7-py2
    ...
```

**Comment by n-rodriguez** [comment]
@myii make your choice https://travis-ci.com/n-rodriguez/telegraf-formula/builds/124134631 :)

**Comment by myii** [comment]
Great job @n-rodriguez!

But what if I want the _new_ matrix available in the `template-formula`...?

* [`kitchen.yml`](https://github.com/saltstack-formulas/template-formula/blob/7dc422a/kitchen.yml)
* [`.travis.yml`](https://github.com/saltstack-formulas/template-formula/blob/7dc422a/.travis.yml)

Actually, I was going to send you a PR on top of whatever you made here, so how about something closer to the previous `template-formula` setup?

* [`kitchen.yml`](https://github.com/saltstack-formulas/template-formula/blob/4a71611/kitchen.yml)
* [`.travis.yml`](https://github.com/saltstack-formulas/template-formula/blob/4a71611/.travis.yml)

**Comment by n-rodriguez** [comment]
ping @myii

**Comment by myii** [comment]
Closing, since replaced by https://github.com/saltstack-formulas/telegraf-formula/issues/1.
